// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  // @ts-expect-error Async Server Component
  article_embed_video_component: dynamic(() => import('./ArticleEmbedVideoComponent')),
  article_screenshot_component: dynamic(() => import('./ArticleScreenshotComponent')),
  text: dynamic(() => import('./Text'))
}
