import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

interface IRootLayout {
  children: React.ReactNode
}

export default function RootLayout({ children }: IRootLayout) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
